language: objective-c
osx_image: xcode7.2
before_install:
  - brew update
  - brew install carthage
install:
  - carthage bootstrap --verbose
script: 
  - xctool test -workspace MVVMKit.xcworkspace -scheme MVVMKit-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
branches:
  only:
    - master
    - develop