language: objective-c
xcode_workspace: MVVMKit.xcworkspace
before_install:
  - brew update
  - brew upgrade xctool
install: 
  - pod install
xcode_scheme: MVVMKitTests
xcode_sdk: iphonesimulator9.1
osx_image: xcode7.1
branches:
  only:
    - master
    - develop