language: objective-c
xcode_workspace: MVVMKit.xcworkspace
xcode_scheme: MVVMKitTests
xcode_sdk: iphonesimulator9.1
osx_image: xcode7.1
before_install:
  - brew update
  - brew install carthage
install:
  - carthage bootstrap --verbose
branches:
  only:
    - master
    - develop